"""fix type otp_code in user table

Revision ID: 475cf8011cb1
Revises: ac96932bd5e8
Create Date: 2026-02-22 10:21:01.866920

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "475cf8011cb1"
down_revision: Union[str, Sequence[str], None] = "ac96932bd5e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
