"""fix category relation

Revision ID: 7e2037972705
Revises: a0e738ad0943
Create Date: 2026-01-15 12:16:11.706696

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7e2037972705"
down_revision: Union[str, Sequence[str], None] = "a0e738ad0943"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Preserve existing category data: rename old table `categorys` -> `categories`.
    # This keeps existing IDs referenced by `products.category_id` intact.
    op.rename_table("categorys", "categories")
    # If needed, you can add additional ALTER COLUMN operations here to match new schema.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "products", type_="foreignkey")
    op.create_foreign_key(
        op.f("products_category_id_fkey"),
        "products",
        "categorys",
        ["category_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_table(
        "categorys",
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("categorys_pkey")),
    )
    op.drop_table("categories")
    # ### end Alembic commands ###
