"""increase_invoices_link_to_text

Revision ID: 941c2d80aa88
Revises: 78706e9aa94b
Create Date: 2026-03-27 11:17:12.743985

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "941c2d80aa88"
down_revision: Union[str, Sequence[str], None] = "78706e9aa94b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "invoices",
        "link",
        existing_type=sa.VARCHAR(length=256),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.drop_constraint(op.f("invoices_uid_key"), "invoices", type_="unique")
    op.drop_constraint(
        op.f("order_products_product_id_fkey"),
        "order_products",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "order_products", "products", ["product_id"], ["id"]
    )
    op.drop_constraint(
        op.f("promocode_actions_user_id_fkey"),
        "promocode_actions",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("promocode_actions_promo_id_fkey"),
        "promocode_actions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "promocode_actions", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        None, "promocode_actions", "promocodes", ["promo_id"], ["id"]
    )
    op.drop_column("promocode_actions", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "promocode_actions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    )
    op.drop_constraint(None, "promocode_actions", type_="foreignkey")
    op.drop_constraint(None, "promocode_actions", type_="foreignkey")
    op.create_foreign_key(
        op.f("promocode_actions_promo_id_fkey"),
        "promocode_actions",
        "promocodes",
        ["promo_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("promocode_actions_user_id_fkey"),
        "promocode_actions",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "order_products", type_="foreignkey")
    op.create_foreign_key(
        op.f("order_products_product_id_fkey"),
        "order_products",
        "products",
        ["product_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint(
        op.f("invoices_uid_key"),
        "invoices",
        ["uid"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "invoices",
        "link",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=256),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
