"""change otp_code > otp_secret

Revision ID: a690a0590927
Revises: 475cf8011cb1
Create Date: 2026-02-22 12:44:09.079081

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a690a0590927"
down_revision: Union[str, Sequence[str], None] = "475cf8011cb1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("otp_secret", sa.String(), nullable=True))
    op.drop_column("users", "otp_code")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("otp_code", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("users", "otp_secret")
    # ### end Alembic commands ###
