"""invoice, user, promocodes

Revision ID: ad896d6a73e5
Revises: 33f31b3b0b5d
Create Date: 2026-02-22 11:18:18.541069

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ad896d6a73e5"
down_revision: Union[str, Sequence[str], None] = "33f31b3b0b5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
