"""add user role

Revision ID: cc8b2c954adc
Revises: 9d6e39ac139d
Create Date: 2026-01-19 12:48:29.180271

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "cc8b2c954adc"
down_revision: Union[str, Sequence[str], None] = "9d6e39ac139d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    roleenum = sa.Enum("user", "employee", "admin", name="roleenum")
    roleenum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "users",
        sa.Column(
            "role",
            roleenum,
            nullable=False,
            server_default="user",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    roleenum = sa.Enum("user", "employee", "admin", name="roleenum")
    roleenum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
