"""Initial revision

Revision ID: f3e1cd1ad675
Revises: 
Create Date: 2026-03-28 11:26:39.589837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3e1cd1ad675'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_invoices_uid'), 'invoices', type_='unique')
    op.drop_index(op.f('uq_users_token_not_null'), table_name='users', postgresql_where='(token IS NOT NULL)')
    op.create_unique_constraint(None, 'users', ['token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('uq_users_token_not_null'), 'users', ['token'], unique=True, postgresql_where='(token IS NOT NULL)')
    op.create_unique_constraint(op.f('uq_invoices_uid'), 'invoices', ['uid'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
